"""add answers to activity participants

Revision ID: c90e2e5669af
Revises: 
Create Date: 2025-01-27 15:18:29.400069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90e2e5669af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.drop_column('answers')

    # ### end Alembic commands ###
