"""empty message

Revision ID: ca9943446d13
Revises: b9139fd41694
Create Date: 2025-02-03 21:08:29.634081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9943446d13'
down_revision = 'b9139fd41694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('structure_shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downloads', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('structure_shares', schema=None) as batch_op:
        batch_op.drop_column('downloads')

    # ### end Alembic commands ###
